intarchboard/draft-path-signals-collaboration

- draft-iab-path-signals-collaboration.md
This is what I’ve written based on our discussion the week before IETF 110, as an attempt to write down the high level guidance and principles we could provide (from my perspective). I’m not sure the best way that this meshes with the current structure, but wanted to share to start a discussion.
> Pull in text to summarize principles

- draft-iab-path-signals-collaboration.md
> New proposed abstract

- draft-iab-path-signals-collaboration.md
> Discuss directions of communication and trust

- draft-iab-path-signals-collaboration.md
This partly address #21.
The second paragraph still talks a lot about encryption. I personally think this is a good thing, but we can also cut at least the last sentence if others think that's better...?
There is also issue #23 which is about layers in the asbtract. The abstract still talks about layers but I'm fine to remove that if we agree we want to; not sure we agreed on this issue yet...?
> New abstract

- draft-iab-path-signals-collaboration.md
Some of these changes will create a merge conflict with my other PR but want to keep them separate to people can review them easily. We just need to remember to apply the removal or the word path also to PR #33 (if accepted).
> Small edits based on comments from Luis M. Contreras

- draft-iab-path-signals-collaboration.md
> Add a section for "limiting impact of information"

- draft-iab-path-signals-collaboration.md
> Rework principles scope

- draft-iab-path-signals-collaboration.md
> Proposal for consent section

- draft-iab-path-signals-collaboration.md
Suggested resolution for issue #54
> Suggested-resolution-issue-54

- draft-iab-path-signals-collaboration.md
Suggested resolution to issue #66
> Suggested-resolution-issue-66

- draft-iab-path-signals-collaboration.md
Attempting to solve Robin's editorial comments from issue #59
> Suggested-resolution-issue-59

- draft-iab-path-signals-collaboration.md
Suggested resolution for issue #64
> Suggested-resolution-issue-64

- draft-iab-path-signals-collaboration.md
Suggested resolution for issue #57
> Suggested-resolution-issue-57

- draft-iab-path-signals-collaboration.md
addresses #63 - M4: Question / principle better alignment
(and two nit fixes)
> Adding one more question and clarification on principle of intended distribution

- draft-iab-path-signals-collaboration.md
This is a proposal to add specific text on pervasive monitoring, in response to issue M1
> Suggested-resolution-issue-60 (Update draft-iab-path-signals-collaboration.md)

- draft-iab-path-signals-collaboration.md
Suggested resolution for issue #30
> Suggested-resolution-issue-30

- draft-iab-path-signals-collaboration.md
Suggested resolution for issue #58
> Suggested-resolution-issue-58

- draft-iab-path-signals-collaboration.md
Suggested resolution for issue #52
> Suggested-resolution-issue-52

- draft-iab-path-signals-collaboration.md
Suggested resolution for issue #51
> Suggested-resolution-issue-51

- draft-iab-path-signals-collaboration.md
Suggested resolution for issue #62
> Suggested-resolution-issue-62

- draft-iab-path-signals-collaboration.md
Suggested resolution for issue #53
> Suggested-resolution-issue-53

- draft-iab-path-signals-collaboration.md
Suggested resolution for issue #80
> Suggested-resolution-issue-80

- draft-iab-path-signals-collaboration.md
> Introduction clarification

- draft-iab-path-signals-collaboration.md
fixes #95 
Not sure if I've put this quite at the right please. Please review!
> flow identifiers are path signals
